### PR TITLE
GH-29: Changed boolean args to kwargs

### LINKED ISSUE #29: All boolean args should be kwargs (including private functions)

### PR DESCRIPTION
**Pull request by trag1c**

### CODE REVIEW

**Comment by qexat** [comment]
Thank you for this PR, I appreciate your contribution!

Just a little request: Can you open an issue and mention it in the PR title? I'll merge it once you've done that. Thank you in advance!

**Review by qexat — APPROVED** [review]
Otherwise LGTM

**Comment by trag1c** [comment]
> Thank you for this PR, I appreciate your contribution!
> 
> Just a little request: Can you open an issue and mention it in the PR title? I'll merge it once you've done that. Thank you in advance!

Sure, hope it's correct now 🙏

**Comment by qexat** [comment]
> Sure, hope it's correct now pray

It's fine now, thank you!

**Pull request merged**
